.gitignore
.terraform.lock.hcl
main.tf
modules/iam_group_membership/main.tf
modules/iam_group_membership/outputs.tf
modules/iam_group_membership/variables.tf
outputs.tf
templates/dev-policy.json
templates/infra-policy.json
variables.tf
versions.tf

개발, 인프라 팀원들의 IAM 사용자 계정을 생성하기 위한 iam_group_membership 모듈 추가

add iam_group_membership

---

templates/dev-policy.json

dev-policy 의 json 형식에 문제가 있어서 고침

fix dev group iam policy

---

main.tf
modules/iam_policy/main.tf
modules/iam_policy/outputs.tf
modules/iam_policy/variables.tf
outputs.tf
templates/lambda-policy.json

iam policy module 추가 및 lambda에서 Secrets Manager의 환경 변수에 접근하기 위해 필요한 정책 추가

feat: create iam policy module

---

main.tf
modules/iam_role/main.tf
modules/iam_role/outputs.tf
modules/iam_role/variables.tf
outputs.tf
templates/lambda-assume-role-policy.json

IAM Role을 생성하는 모듈 추가 및 추가한 모듈을 기반으로 lambda에서 사용할 IAM Role 생성

feat: iam role module

---

main.tf
modules/iam_role_policy_attachment/main.tf
modules/iam_role_policy_attachment/outputs.tf
modules/iam_role_policy_attachment/variables.tf

IAM Role에 IAM Policy를 attach해주는 모듈 추가

feat: iam_role_policy attachment module

---

main.tf
modules/s3/main.tf
modules/s3/outputs.tf
modules/s3/variables.tf
outputs.tf
templates/s3-policy.json

정적 웹사이트를 호스팅할 S3 모듈 추가
Resolve: #8

feat: S3 module

---

main.tf
modules/api_gateway/main.tf
modules/api_gateway/outputs.tf
modules/api_gateway/variables.tf
modules/lambda/outputs.tf
outputs.tf

API Gateway를 생성하는 모듈 추가
API Gateway가 lambda 에 접근하기 위해 `aws_lambda_permission` 리소스를 lambda 모듈에 추가가 필요

feat: api gateway module

---

main.tf
modules/cloudfront/main.tf
modules/cloudfront/outputs.tf
modules/cloudfront/variables.tf
modules/s3/outputs.tf
outputs.tf

S3 정적 웹 호스트 앞에서 CDN 역할을 수행할 cloudfront를 구현하였습니다.
Resolve: #14

✨ feat: cloudfront module

---

templates/infra-policy.json

IAM Policy를 생성할 수 있도록 Infra Policy 추가

chore: update create policy

---

main.tf
modules/s3/outputs.tf
outputs.tf

 bug: modify reference

---

templates/infra-policy.json

CloudFront생성에 필요한 iam:PutGroupPolicy 추가

chore: update infra policy

---

main.tf
modules/api_gateway/outputs.tf

ci/cd 과정에 사용될 lambda function name과 api gateway invoke url 추가

feat: add parameter store value for lambda function name, api gateway invoke url

---

templates/infra-policy.json

wafv2 리소스를 생성하기 위해 infra policy에 wafv2 권한에 대한 정책 추가

chore: wafv2 authorization policy

---

modules/lambda/main.tf

SAM 개발 환경에 맞춰 개발되는 각 함수의 파일명에 맞게 handler 파일명 수정

chore: update lambda handler

---

main.tf

람다함수에서 CloudWatch Logs에 로그를 보내기 위한 정책 추가

chore: update lambda role policy

---

main.tf
modules/cloudfront/main.tf

us_east_1 alias 추가
Related to: #55

bug: cloudfront

---

main.tf
templates/s3-policy.json

- test lambda function 추가
- apigateway에 GET /test 추가
- s3-policy에 문법 오류 수정
- lambda layer name parameter store에 추가 (lambda layer ci/cd에 사용될 예정)

feat: add test lambda function and api gateway attachment

---

templates/infra-policy.json
templates/sns-topic-policy.json

권한 추가 및 policy 수정
Related to: #73

bug: budget alarm

---

templates/infra-policy.json

권한 문제로 에러가 발생하여 권한을 추가하였습니다.
Related to: #73

✏️ chore: update policy

---

main.tf
modules/lambda/main.tf
modules/lambda/variables.tf

`create_log_subscription_filter` 변수를 추가해 subscription filter 생성 여부를 boolean 값으로 명시할 수 있도록 변경

feat: cloudwatch log group and cloudwatch log subscription filter

---

main.tf
modules/cloudfront/main.tf
modules/cloudfront/variables.tf
modules/waf/main.tf
modules/waf/outputs.tf
modules/waf/variables.tf

WAF에서 발생되는 이상 증상을 Slack에서 알림을 받을 수 있게끔 하였습니다.
Related to: #86

feat: waf alarm

---

main.tf
modules/lambda/main.tf
modules/lambda/variables.tf

lambda 함수를 생성하며 timeout (execution time)을 설정 할 수 있도록 변경

fix: lambda timeout

---

modules/cloudfront/main.tf

fix: Cloudfront

---

main.tf
modules/api_gateway/main.tf
modules/api_gateway/variables.tf

api gateway module에 cors 설정하는 부분 추가

feat: api gateway cors

---

modules/budgets/main.tf

budget 부분에 날짜 부분에 수정이 되어 있지 않아 정정하였습니다.
Related to: #99

chore: change date

---

modules/waf/main.tf

Block할 조건의 요청 건수를 수정하였습니다.
Resolve: #104

chore: update limit

---

main.tf
modules/api_gateway/main.tf
modules/waf/main.tf

aws_cloudwatch_metric_alarm의 dimensions에 Rule을 추가

fix: waf cloudwatch metric alarm add rule

---

modules/waf/main.tf

fix: waf alarm

---

modules/waf/main.tf

정책을 수정한걸 연결해줘야하는데 원본을 연결해서 sns가 수신을 못했습니다.
바보같은..

🐛 fix: waf alarm

---

modules/budgets/main.tf

크레딧을 제외하도록 설정하였고 정책 부분이 잘못 할당되어있어 수정하였습니다.
Related to: #111

fix: budget alarm
